// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphqlmodel

type Node interface {
	IsNode()
}

type MutationResponse struct {
	ID *string `json:"id"`
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}
