// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/google/wire"
	"github.com/sky0621/wolf-bff/src"
	"github.com/sky0621/wolf-bff/src/adapter/controller"
	"github.com/sky0621/wolf-bff/src/adapter/gateway"
	"github.com/sky0621/wolf-bff/src/driver"
	"github.com/sky0621/wolf-bff/src/system"
	"github.com/sky0621/wolf-bff/src/usecase"
)

// Injectors from wire.go:

func build(ctx context.Context, cfg system.Config) (wht.App, error) {
	logger := system.NewLogger(cfg)
	rdb, err := driver.NewRDB(cfg, logger)
	if err != nil {
		return nil, err
	}
	domainWht := gateway.NewWht(logger, rdb)
	usecaseWht := usecase.NewWht(logger, domainWht)
	resolverRoot := controller.NewResolver(usecaseWht)
	web := driver.NewWeb(cfg, logger, resolverRoot)
	app := wht.NewApp(cfg, logger, rdb, web)
	return app, nil
}

// Injectors from wire_local.go:

func buildLocal(ctx context.Context, cfg system.Config) (wht.App, error) {
	logger := system.NewLogger(cfg)
	rdb, err := driver.NewRDB(cfg, logger)
	if err != nil {
		return nil, err
	}
	domainWht := gateway.NewWht(logger, rdb)
	usecaseWht := usecase.NewWht(logger, domainWht)
	resolverRoot := controller.NewResolver(usecaseWht)
	web := driver.NewWeb(cfg, logger, resolverRoot)
	app := wht.NewApp(cfg, logger, rdb, web)
	return app, nil
}

// wire.go:

var commonSet = wire.NewSet(gateway.NewWht, usecase.NewWht, controller.NewResolver, driver.NewWeb, wht.NewApp)
