// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/sky0621/wolf-bff/src"
	"github.com/sky0621/wolf-bff/src/driver"
	"github.com/sky0621/wolf-bff/src/system"
)

// Injectors from di.go:

func di(cfg system.Config) wht.App {
	rdb := driver.NewRDB(cfg)
	web := driver.NewWeb(cfg)
	app := wht.NewApp(cfg, rdb, web)
	return app
}

// di.go:

var set = wire.NewSet(system.NewLogger, driver.NewRDB, driver.NewWeb, wht.NewApp)
