// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/sky0621/wolf-bff/src"
	"github.com/sky0621/wolf-bff/src/driver"
	"github.com/sky0621/wolf-bff/src/system"
)

// Injectors from wire.go:

func build(ctx context.Context, cfg system.Config) (wht.App, error) {
	logger := system.NewLogger(cfg)
	rdb, err := driver.NewRDB(cfg, logger)
	if err != nil {
		return nil, err
	}
	web := driver.NewWeb(cfg, logger)
	app := wht.NewApp(cfg, logger, rdb, web)
	return app, nil
}

// Injectors from wire_local.go:

func buildLocal(ctx context.Context, cfg system.Config) (wht.App, error) {
	logger := system.NewLogger(cfg)
	rdb, err := driver.NewRDB(cfg, logger)
	if err != nil {
		return nil, err
	}
	web := driver.NewWeb(cfg, logger)
	app := wht.NewApp(cfg, logger, rdb, web)
	return app, nil
}
